# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  (1..3).each do |i|
    config.vm.define "aggregator-#{i}" do |aggregator|
	  # Use debian, which is simular to Rasbian
      aggregator.vm.box = "bento/debian-8.2"
	  aggregator.vm.network "private_network", ip: "192.168.200.#{100+i}"
	  # Fix "rsync" could not be found error.
	  # http://stackoverflow.com/questions/34176041/vagrant-with-virtualbox-on-windows10-rsync-could-not-be-found-on-your-path
	  # aggregator.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    end
  end
end